/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cramers.rule;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author sasbeb
 */
public class Cramers_Rule_Input extends javax.swing.JFrame {

    /**
     * Creates new form Cramers_Rule_Input
     */
    public Cramers_Rule_Input() {
        initComponents();
        initCoefficientsTableModel(2);
        initTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        apply = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();
        components = new javax.swing.JPanel();
        coeffients = new javax.swing.JTable();
        answers = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cramer's Rule");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        apply.setText("Apply");
        apply.setToolTipText("");
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        components.setLayout(new java.awt.BorderLayout());

        coeffients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        components.add(coeffients, java.awt.BorderLayout.CENTER);

        answers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        components.add(answers, java.awt.BorderLayout.LINE_END);

        header.setLayout(new java.awt.BorderLayout());
        components.add(header, java.awt.BorderLayout.PAGE_START);

        scrollpane.setViewportView(components);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(apply)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(remove)
                        .addComponent(clear)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apply)
                    .addComponent(cancel))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int ccount = coeffients.getColumnCount();
        TableModel model = coeffients.getModel();
        CoeffientsTableModel coeffients_model = (model instanceof CoeffientsTableModel) ? (CoeffientsTableModel) model : null;
        if (coeffients_model != null && ccount < coeffients_model.getMaxCoefficentCounts()) {
            initCoefficientsTableModel(ccount + 1);
            pack();
        }
    }//GEN-LAST:event_addActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        // TODO add your handling code here:
        TableModel model = coeffients.getModel();
        CoeffientsTableModel coeffients_model = (model instanceof CoeffientsTableModel) ? (CoeffientsTableModel) model : null;
        if (coeffients_model != null) {
            TableModel answsers_model = coeffients_model.getAnswersTableModel();
            int ccount = coeffients_model.getColumnCount();
            int rcount = coeffients_model.getRowCount();
            String[] coefficents = new String[ccount];
            double[][] values;
            double[] answers;
            for (int i = 0; i < ccount; i++) {
                coefficents[i] = coeffients_model.getColumnName(i);
            }
            List<List<Number>> c_data = new ArrayList();
            List<Number> a_data = new ArrayList();
            boolean ok = true;
            for (int row = 0; ok && row < rcount; row++) {
                List<Number> data = new ArrayList();
                c_data.add(data);
                for (int column = 0; ok && column < ccount; column++) {
                    Object o = coeffients_model.getValueAt(row, column);
                    if (o instanceof Number) {
                        data.add((Number) o);
                    } else {
                        String s = String.valueOf(o).trim();
                        try {
                            Double d = new Double(s);
                            data.add(d);
                        } catch (Exception e) {
                            e.printStackTrace();
                            ok = false;
                        }
                    }
                }
            }
            for (int row = 0; ok && row < rcount; row++) {
                Object o = answsers_model.getValueAt(row, 0);
                if (o instanceof Number) {
                    a_data.add((Number) o);
                } else {
                    String s = String.valueOf(o).trim();
                    try {
                        Double d = new Double(s);
                        a_data.add(d);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
                        ok = false;
                    }
                }
            }
            if (ok) {
                values = new double[rcount][ccount];
                for (int i = 0; i < rcount; i++) {
                    List<Number> data = c_data.get(i);
                    for (int j = 0; j < ccount; j++) {
                        Number n = data.get(j);
                        values[i][j] = n.doubleValue();
                    }
                }
                answers = new double[rcount];
                for (int i = 0; i < rcount; i++) {
                    Number n = a_data.get(i);
                    answers[i] = n.doubleValue();
                }
                solveCramer(coefficents, values, answers);
            }
        }
    }//GEN-LAST:event_applyActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        int rcount = coeffients.getRowCount();
        if (rcount > 2) {
            initCoefficientsTableModel(rcount - 1);
            pack();
        }
    }//GEN-LAST:event_removeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        initCoefficientsTableModel(2);
        pack();
    }//GEN-LAST:event_clearActionPerformed
    private void initCoefficientsTableModel(int count) {
        //populate the table models
        CoeffientsTableModel coeffients_model = new CoeffientsTableModel(count, count);
        coeffients.setModel(coeffients_model);
        JTableHeader t_header = coeffients.getTableHeader();
        t_header.setReorderingAllowed(false);
        JLabel l = (JLabel) t_header.getDefaultRenderer();
        l.setHorizontalAlignment(JLabel.CENTER);
        header.add(t_header, BorderLayout.CENTER);


        answers.setModel(coeffients_model.getAnswersTableModel());
        t_header = answers.getTableHeader();
        l = (JLabel) t_header.getDefaultRenderer();
        l.setHorizontalAlignment(JLabel.CENTER);
        header.add(t_header, BorderLayout.EAST);

        answers.setSelectionModel(coeffients.getSelectionModel());
        coeffients.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        answers.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
    }

    private TableModel copytoMatrixTableModel(double[][] values) {
        TableModel model = new DefaultTableModel(values.length, values.length) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }

            public Class getColumnClass(int columnIndex) {
                return Double.class;
            }
        };
        int ccount = model.getColumnCount();
        int rcount = model.getColumnCount();
        for (int row = 0; row < rcount; row++) {
            for (int col = 0; col < ccount; col++) {
                model.setValueAt(values[row][col], row, col);
            }
        }
        return model;
    }

    private boolean solveCramer(String[] coefficents, double[][] values, double[] answers) {
        int rcount = answers.length;
        int ccount = coefficents.length;
        //create all the matricies and solve them
        JPanel grid = new JPanel(new GridLayout(coefficents.length + 1, 1, 8, 8));
        //add the base matrix
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setTitle("Cramer's Rule: Solution");
        frame.add(grid);
        int which = -1;
        double dn = 1;
        do {
            double[][] data = new double[values.length][values.length];
            for (int row = 0; row < data.length; row++) {
                for (int col = 0; col < data.length; col++) {
                    data[row][col] = values[row][col];
                }
            }
            JPanel p = new JPanel(new BorderLayout(5, 5));
            String label = "D ";
            if (which != -1) {
                label = "D" + coefficents[which];
                //replace the coefficent column with the answer column
                for (int row = 0; row < answers.length; row++) {
                    data[row][which] = answers[row];
                }
            }
            double answer = 0.0;
            if (which > -1) {
                answer = computeDeterminant(data) / dn;
            } else {
                dn = computeDeterminant(data);
                answer = dn;
            }
            //JLabel l = new JLabel(label);
            //l.setHorizontalAlignment(JLabel.LEFT);
            //p.add(l, BorderLayout.NORTH);
            p.setBorder(BorderFactory.createTitledBorder(label));
            JTable matrix = new DeterminantTable(which, copytoMatrixTableModel(data));
            p.add(matrix, BorderLayout.CENTER);
            NumberFormat formatter = NumberFormat.getInstance();
            label = (which == -1) ? "Coefficient Determinant" : coefficents[which];
            JLabel l = new JLabel(label += " = " + formatter.format(answer));
            l.setHorizontalAlignment(JLabel.RIGHT);
            p.add(l, BorderLayout.SOUTH);
            grid.add(p);
            which++;
        } while (which < coefficents.length);
        frame.pack();
        frame.setVisible(true);
        return true;
    }

    private double computeDeterminant(double[][] data) {
        int ccount = data.length;
        NumberFormat format = NumberFormat.getInstance();
        double value = 0.0;
        if (ccount == 2) {
            double a = data[0][0];
            double b = data[0][1];
            double c = data[1][0];
            double d = data[1][1];
            return (a * d) - (b * c);
        }
        boolean pos = true;
        for (int d_col = 0; d_col < ccount; d_col++) {
            double d = data[0][d_col];
            double[][] n_data = new double[ccount - 1][ccount - 1];
            int n_row = 0;
            for (int row = 1; row < ccount; row++) {
                int n_col = 0;
                for (int col = 0; col < ccount; col++) {
                    if (d_col != col) {
                        n_data[n_row][n_col++] = data[row][col];
                    }
                }
                n_row++;
            }
            double d_value = d * computeDeterminant(n_data);
            if (pos) {
                value += d_value;
                pos = false;
            } else {
                value -= d_value;
                pos = true;
            }
        }
        return value;
    }

    private void initTest() {
        //coefficients
        double[][] c_data = new double[][]{
            {1, 2, 3, 4},
            {2, 1, 1, -1},
            {3, 1, 4, 3},
            {-2, 6, 4, 20}
        };
        //answers        
        double[] a_data = new double[]{
            10,
            1,
            22,
            18
        };
        initCoefficientsTableModel(a_data.length);
        int ccount = coeffients.getColumnCount();
        int rcount = coeffients.getRowCount();
        for (int row = 0; row < rcount; row++) {
            for (int col = 0; col < ccount; col++) {
                coeffients.setValueAt(c_data[row][col], row, col);
            }
        }
        for (int row = 0; row < rcount; row++) {
            answers.setValueAt(a_data[row], row, 0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (Exception e) {
            try {
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            } catch (Exception ex) {
            }
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cramers_Rule_Input().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTable answers;
    private javax.swing.JButton apply;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JTable coeffients;
    private javax.swing.JPanel components;
    private javax.swing.JPanel header;
    private javax.swing.JButton remove;
    private javax.swing.JScrollPane scrollpane;
    // End of variables declaration//GEN-END:variables

    class AnswersTableModel extends DefaultTableModel {

        public AnswersTableModel(int rowCount, int columnCount) {
            super(rowCount, columnCount);
        }

        public String getColumnName(int column) {
            return (column == 0) ? "Answers" : super.getColumnName(column);
        }

        public Class getColumnClass(int columnIndex) {
            return Double.class;
        }
    }

    class CoeffientsTableModel extends DefaultTableModel {

        String[] _vars = {
            "x",
            "y",
            "z",
            "a",
            "b",
            "c",
            "d",};
        private AnswersTableModel _answers;

        public CoeffientsTableModel(int rowCount, int columnCount) {
            super(rowCount, columnCount);
        }

        public String getColumnName(int column) {
            return ((column > -1) && (column < _vars.length)) ? _vars[column] : super.getColumnName(column);
        }

        public int getMaxCoefficentCounts() {
            return _vars.length;
        }

        public TableModel getAnswersTableModel() {
            int rcount = getRowCount();
            _answers = ((_answers != null) && _answers.getRowCount() == rcount) ? _answers : null;
            if (_answers == null) {
                _answers = new AnswersTableModel(rcount, 1);
            }
            return _answers;
        }

        public Class getColumnClass(int columnIndex) {
            return Double.class;
        }
    }

    class DeterminantTable extends JTable {

        int _which = -1;

        public DeterminantTable(int which, TableModel model) {
            super(model);
            _which = which;
        }

        public Component prepareRenderer(TableCellRenderer r, int data, int column) {
            Component c = super.prepareRenderer(r, data, column);
            if ((_which > -1) && (column == _which)) {
                c.setForeground(Color.red);
            } else {
                c.setForeground(Color.blue);
            }
            return c;
        }
    }
}
